name: image_carousel_gallery_example
description: Example app for image_carousel_gallery.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_carousel_gallery:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
