name: image_carousel_gallery
description: A new Flutter package for creating an image carousel gallery with an animated image slider.
version: 0.0.3
homepage: https://github.com/ipawanghimire/image_carousel_gallery

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


